/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.duoc.clinica.graficas;

import cl.duoc.clinica.entidades.Atencion;
import cl.duoc.clinica.entidades.Especialidad;
import cl.duoc.clinica.entidades.SistemaDeSalud;
import cl.duoc.clinica.negocio.negAtencion;
import cl.duoc.clinica.negocio.negEspecialidad;
import cl.duoc.clinica.negocio.negSistemaDeSalud;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Esteb
 */
public class frmMantenedorAtenciones extends javax.swing.JFrame {
    private HashMap<String,Integer> mapEspecialidad = new HashMap<String,Integer>();
    private HashMap<String,Integer> mapSistemaDeSalud = new HashMap<String,Integer>();
    SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
    /**
     * Creates new form MantenedorAtenciones
     */
    public frmMantenedorAtenciones() {
        initComponents();
        establecerId();
        llenarCombos();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenuBg = new javax.swing.JPanel();
        agregarButtonMA = new javax.swing.JPanel();
        agregartxt = new javax.swing.JLabel();
        eliminarButtonMA = new javax.swing.JPanel();
        eliminartxt = new javax.swing.JLabel();
        modificarButtonMA = new javax.swing.JPanel();
        modificartxt = new javax.swing.JLabel();
        mainmenuButtonMA = new javax.swing.JPanel();
        volvermenutxt = new javax.swing.JLabel();
        cerrarsesionButtonMA = new javax.swing.JPanel();
        cerrarsesiontxt = new javax.swing.JLabel();
        OPCIONEStxt = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        TitleMenu = new javax.swing.JPanel();
        Icon = new javax.swing.JLabel();
        Tiltetxt = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ZonaBg = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        txtIdAtencion = new javax.swing.JTextField();
        lblIdAtencion = new javax.swing.JLabel();
        lblRutPaciente = new javax.swing.JLabel();
        txtRutPaciente = new javax.swing.JTextField();
        lblNombrePaciente = new javax.swing.JLabel();
        txtNombrePaciente = new javax.swing.JTextField();
        lblFechaNacimiento = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JTextField();
        lblSistemaDeSalud = new javax.swing.JLabel();
        cmbSistemaDeSalud = new javax.swing.JComboBox<>();
        lblEspecialidad = new javax.swing.JLabel();
        cmbEspecialidad = new javax.swing.JComboBox<>();
        lblFechaNacimiento1 = new javax.swing.JLabel();
        ZonaTableBg = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAtenciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainMenuBg.setBackground(new java.awt.Color(0, 135, 193));

        agregarButtonMA.setBackground(new java.awt.Color(0, 0, 255));
        agregarButtonMA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarButtonMAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarButtonMAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregarButtonMAMouseExited(evt);
            }
        });

        agregartxt.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        agregartxt.setForeground(new java.awt.Color(255, 255, 255));
        agregartxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregartxt.setText("AGREGAR");

        javax.swing.GroupLayout agregarButtonMALayout = new javax.swing.GroupLayout(agregarButtonMA);
        agregarButtonMA.setLayout(agregarButtonMALayout);
        agregarButtonMALayout.setHorizontalGroup(
            agregarButtonMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agregartxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        agregarButtonMALayout.setVerticalGroup(
            agregarButtonMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agregartxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        eliminarButtonMA.setBackground(new java.awt.Color(0, 0, 255));
        eliminarButtonMA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarButtonMAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminarButtonMAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminarButtonMAMouseExited(evt);
            }
        });

        eliminartxt.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        eliminartxt.setForeground(new java.awt.Color(255, 255, 255));
        eliminartxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eliminartxt.setText("ELIMINAR");

        javax.swing.GroupLayout eliminarButtonMALayout = new javax.swing.GroupLayout(eliminarButtonMA);
        eliminarButtonMA.setLayout(eliminarButtonMALayout);
        eliminarButtonMALayout.setHorizontalGroup(
            eliminarButtonMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eliminartxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        eliminarButtonMALayout.setVerticalGroup(
            eliminarButtonMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eliminartxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        modificarButtonMA.setBackground(new java.awt.Color(0, 0, 255));
        modificarButtonMA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarButtonMAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarButtonMAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarButtonMAMouseExited(evt);
            }
        });

        modificartxt.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        modificartxt.setForeground(new java.awt.Color(255, 255, 255));
        modificartxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modificartxt.setText("MODIFICAR");

        javax.swing.GroupLayout modificarButtonMALayout = new javax.swing.GroupLayout(modificarButtonMA);
        modificarButtonMA.setLayout(modificarButtonMALayout);
        modificarButtonMALayout.setHorizontalGroup(
            modificarButtonMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modificartxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        modificarButtonMALayout.setVerticalGroup(
            modificarButtonMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modificartxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        mainmenuButtonMA.setBackground(new java.awt.Color(204, 0, 153));
        mainmenuButtonMA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainmenuButtonMAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainmenuButtonMAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mainmenuButtonMAMouseExited(evt);
            }
        });

        volvermenutxt.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        volvermenutxt.setForeground(new java.awt.Color(255, 255, 255));
        volvermenutxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volvermenutxt.setText("MENU PRINCIPAL");

        javax.swing.GroupLayout mainmenuButtonMALayout = new javax.swing.GroupLayout(mainmenuButtonMA);
        mainmenuButtonMA.setLayout(mainmenuButtonMALayout);
        mainmenuButtonMALayout.setHorizontalGroup(
            mainmenuButtonMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(volvermenutxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainmenuButtonMALayout.setVerticalGroup(
            mainmenuButtonMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(volvermenutxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        cerrarsesionButtonMA.setBackground(new java.awt.Color(204, 0, 153));
        cerrarsesionButtonMA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarsesionButtonMAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarsesionButtonMAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarsesionButtonMAMouseExited(evt);
            }
        });

        cerrarsesiontxt.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        cerrarsesiontxt.setForeground(new java.awt.Color(255, 255, 255));
        cerrarsesiontxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrarsesiontxt.setText("CERRAR SESION");

        javax.swing.GroupLayout cerrarsesionButtonMALayout = new javax.swing.GroupLayout(cerrarsesionButtonMA);
        cerrarsesionButtonMA.setLayout(cerrarsesionButtonMALayout);
        cerrarsesionButtonMALayout.setHorizontalGroup(
            cerrarsesionButtonMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrarsesiontxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cerrarsesionButtonMALayout.setVerticalGroup(
            cerrarsesionButtonMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrarsesiontxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        OPCIONEStxt.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        OPCIONEStxt.setForeground(new java.awt.Color(255, 255, 255));
        OPCIONEStxt.setText("OPCIONES");

        javax.swing.GroupLayout MainMenuBgLayout = new javax.swing.GroupLayout(MainMenuBg);
        MainMenuBg.setLayout(MainMenuBgLayout);
        MainMenuBgLayout.setHorizontalGroup(
            MainMenuBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agregarButtonMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(eliminarButtonMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(modificarButtonMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainmenuButtonMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cerrarsesionButtonMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainMenuBgLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuBgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OPCIONEStxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        MainMenuBgLayout.setVerticalGroup(
            MainMenuBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuBgLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(OPCIONEStxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(agregarButtonMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminarButtonMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modificarButtonMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainmenuButtonMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cerrarsesionButtonMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(MainMenuBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 410));

        TitleMenu.setBackground(new java.awt.Color(0, 135, 193));

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbv/images/iconoCLinica.png"))); // NOI18N

        Tiltetxt.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        Tiltetxt.setForeground(new java.awt.Color(255, 255, 255));
        Tiltetxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tiltetxt.setText("MANTENEDOR ATENCIONES");

        javax.swing.GroupLayout TitleMenuLayout = new javax.swing.GroupLayout(TitleMenu);
        TitleMenu.setLayout(TitleMenuLayout);
        TitleMenuLayout.setHorizontalGroup(
            TitleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleMenuLayout.createSequentialGroup()
                .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(TitleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tiltetxt))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        TitleMenuLayout.setVerticalGroup(
            TitleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Icon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TitleMenuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Tiltetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(TitleMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 600, 90));

        ZonaBg.setBackground(new java.awt.Color(0, 135, 193));

        txtIdAtencion.setEditable(false);

        lblIdAtencion.setFont(new java.awt.Font("JetBrains Mono", 0, 11)); // NOI18N
        lblIdAtencion.setForeground(new java.awt.Color(255, 255, 255));
        lblIdAtencion.setText("ID_ATENCION:");

        lblRutPaciente.setFont(new java.awt.Font("JetBrains Mono", 0, 11)); // NOI18N
        lblRutPaciente.setForeground(new java.awt.Color(255, 255, 255));
        lblRutPaciente.setText("RUT PACIENTE:");

        txtRutPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutPacienteKeyTyped(evt);
            }
        });

        lblNombrePaciente.setFont(new java.awt.Font("JetBrains Mono", 0, 11)); // NOI18N
        lblNombrePaciente.setForeground(new java.awt.Color(255, 255, 255));
        lblNombrePaciente.setText("NOMBRE PACIENTE:");

        txtNombrePaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombrePacienteKeyTyped(evt);
            }
        });

        lblFechaNacimiento.setFont(new java.awt.Font("JetBrains Mono", 0, 11)); // NOI18N
        lblFechaNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaNacimiento.setText("FECHA NACIMIENTO:");

        txtFechaNacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaNacimientoKeyTyped(evt);
            }
        });

        lblSistemaDeSalud.setFont(new java.awt.Font("JetBrains Mono", 0, 11)); // NOI18N
        lblSistemaDeSalud.setForeground(new java.awt.Color(255, 255, 255));
        lblSistemaDeSalud.setText("SISTEMA DE SALUD:");

        cmbSistemaDeSalud.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbSistemaDeSalud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSistemaDeSaludActionPerformed(evt);
            }
        });

        lblEspecialidad.setFont(new java.awt.Font("JetBrains Mono", 0, 11)); // NOI18N
        lblEspecialidad.setForeground(new java.awt.Color(255, 255, 255));
        lblEspecialidad.setText("ESPECIALIDAD:");

        lblFechaNacimiento1.setFont(new java.awt.Font("JetBrains Mono", 0, 11)); // NOI18N
        lblFechaNacimiento1.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaNacimiento1.setText("\"dd-MM-yyyy\"");

        javax.swing.GroupLayout ZonaBgLayout = new javax.swing.GroupLayout(ZonaBg);
        ZonaBg.setLayout(ZonaBgLayout);
        ZonaBgLayout.setHorizontalGroup(
            ZonaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZonaBgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ZonaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator5)
                    .addGroup(ZonaBgLayout.createSequentialGroup()
                        .addGroup(ZonaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ZonaBgLayout.createSequentialGroup()
                                .addComponent(lblNombrePaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ZonaBgLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblRutPaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRutPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ZonaBgLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblIdAtencion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(ZonaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ZonaBgLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblFechaNacimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFechaNacimiento1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZonaBgLayout.createSequentialGroup()
                        .addGroup(ZonaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ZonaBgLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ZonaBgLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblSistemaDeSalud)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbSistemaDeSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ZonaBgLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(ZonaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(ZonaBgLayout.createSequentialGroup()
                                        .addComponent(lblEspecialidad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(73, 73, 73))))
        );
        ZonaBgLayout.setVerticalGroup(
            ZonaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZonaBgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ZonaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ZonaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIdAtencion))
                    .addGroup(ZonaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFechaNacimiento)
                        .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFechaNacimiento1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ZonaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ZonaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSistemaDeSalud)
                    .addComponent(cmbSistemaDeSalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRutPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRutPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ZonaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ZonaBgLayout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ZonaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombrePaciente)
                            .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ZonaBgLayout.createSequentialGroup()
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ZonaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEspecialidad)
                            .addComponent(cmbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(ZonaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ZonaBgLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ZonaBgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(ZonaBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 600, 140));

        ZonaTableBg.setBackground(new java.awt.Color(0, 135, 193));
        ZonaTableBg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 115, 164)));

        tblAtenciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_ATENCION", "RUT ", "NOMBRE", "EDAD", "FECHA NACIMIENTO", "ESPECIALIDAD", "SISTEMA DE SALUD"
            }
        ));
        tblAtenciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAtencionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAtenciones);

        javax.swing.GroupLayout ZonaTableBgLayout = new javax.swing.GroupLayout(ZonaTableBg);
        ZonaTableBg.setLayout(ZonaTableBgLayout);
        ZonaTableBgLayout.setHorizontalGroup(
            ZonaTableBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
            .addGroup(ZonaTableBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ZonaTableBgLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        ZonaTableBgLayout.setVerticalGroup(
            ZonaTableBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
            .addGroup(ZonaTableBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ZonaTableBgLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(ZonaTableBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 600, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarButtonMAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarButtonMAMouseEntered
        agregarButtonMA.setBackground(Color.ORANGE);
    }//GEN-LAST:event_agregarButtonMAMouseEntered

    private void agregarButtonMAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarButtonMAMouseExited
        agregarButtonMA.setBackground(Color.BLUE);
    }//GEN-LAST:event_agregarButtonMAMouseExited

    private void eliminarButtonMAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarButtonMAMouseEntered
        eliminarButtonMA.setBackground(Color.ORANGE);
    }//GEN-LAST:event_eliminarButtonMAMouseEntered

    private void eliminarButtonMAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarButtonMAMouseExited
        eliminarButtonMA.setBackground(Color.BLUE);
    }//GEN-LAST:event_eliminarButtonMAMouseExited

    private void modificarButtonMAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarButtonMAMouseEntered
        modificarButtonMA.setBackground(Color.ORANGE);
    }//GEN-LAST:event_modificarButtonMAMouseEntered

    private void modificarButtonMAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarButtonMAMouseExited
        modificarButtonMA.setBackground(Color.BLUE);
    }//GEN-LAST:event_modificarButtonMAMouseExited

    private void mainmenuButtonMAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainmenuButtonMAMouseEntered
        mainmenuButtonMA.setBackground(Color.ORANGE);
    }//GEN-LAST:event_mainmenuButtonMAMouseEntered

    private void mainmenuButtonMAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainmenuButtonMAMouseExited
        mainmenuButtonMA.setBackground(new java.awt.Color(204, 0, 153));
    }//GEN-LAST:event_mainmenuButtonMAMouseExited

    private void cerrarsesionButtonMAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarsesionButtonMAMouseEntered
        cerrarsesionButtonMA.setBackground(Color.orange);
    }//GEN-LAST:event_cerrarsesionButtonMAMouseEntered

    private void cerrarsesionButtonMAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarsesionButtonMAMouseExited
        cerrarsesionButtonMA.setBackground(new java.awt.Color(204, 0, 153));
    }//GEN-LAST:event_cerrarsesionButtonMAMouseExited

    private void cerrarsesionButtonMAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarsesionButtonMAMouseClicked
        frmLogin log = new frmLogin();
        log.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cerrarsesionButtonMAMouseClicked

    private void mainmenuButtonMAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainmenuButtonMAMouseClicked
        frmMenuP mm = new frmMenuP();
        mm.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_mainmenuButtonMAMouseClicked

    private void tblAtencionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAtencionesMouseClicked

        int selectedRow = tblAtenciones.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione atencion");
        } else {

            cmbSistemaDeSalud.setSelectedItem((String)tblAtenciones.getValueAt(selectedRow, 6));
            txtIdAtencion.setText(String.valueOf(tblAtenciones.getValueAt(selectedRow, 0)));
            txtRutPaciente.setText((String) tblAtenciones.getValueAt(selectedRow, 1));
            txtNombrePaciente.setText((String) tblAtenciones.getValueAt(selectedRow, 2));
            txtFechaNacimiento.setText((format.format(tblAtenciones.getValueAt(selectedRow, 4))));
            cmbEspecialidad.setSelectedItem((String)tblAtenciones.getValueAt(selectedRow, 5));
        }
    }//GEN-LAST:event_tblAtencionesMouseClicked

    private void txtNombrePacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombrePacienteKeyTyped
        char key = evt.getKeyChar();

        if (Character.isDigit(key)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo letras permitidas en este campo");
        }
    }//GEN-LAST:event_txtNombrePacienteKeyTyped

    private void cmbSistemaDeSaludActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSistemaDeSaludActionPerformed

    }//GEN-LAST:event_cmbSistemaDeSaludActionPerformed

    private void agregarButtonMAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarButtonMAMouseClicked
        
        
        try {
            int idAtencion = Integer.parseInt(txtIdAtencion.getText());
            String rut = txtRutPaciente.getText();
            String nombre = txtNombrePaciente.getText();
            Date fechaNacimiento = format.parse(txtFechaNacimiento.getText());
            int idEspecialidad = mapEspecialidad.get(cmbEspecialidad.getSelectedItem().toString());
            int idSistemaDeSalud = mapSistemaDeSalud.get(cmbSistemaDeSalud.getSelectedItem().toString());
            
            Atencion at = new Atencion();
            at.setIdAtencion(idAtencion);
            at.setRutPaciente(rut);
            at.setNombrePaciente(nombre);
            at.setFechaNacimientoPaciente(fechaNacimiento);
            at.setIdEspecialidad(idEspecialidad);
            at.setIdSistemaDeSalud(idSistemaDeSalud);
            
            if(new negAtencion().agregarAtencion(at)) {
                JOptionPane.showMessageDialog(this, "Atencion registrada");
                refrescaTabla();
                limpiarDatos();
            } else {
                JOptionPane.showMessageDialog(this, "Atencion no registrada");
                refrescaTabla();
                limpiarDatos();
            }
            
        } catch (ParseException ex) {
            Logger.getLogger(frmMantenedorAtenciones.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Atencion no registrada");
            refrescaTabla();
            limpiarDatos();
        }
    }//GEN-LAST:event_agregarButtonMAMouseClicked

    private void eliminarButtonMAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarButtonMAMouseClicked
        
        Atencion at = new Atencion();
        at.setIdAtencion(Integer.parseInt(txtIdAtencion.getText()));
        
        if (new negAtencion().eliminarAtencion(at)) {
            JOptionPane.showMessageDialog(this, "Atencion eliminada");
            refrescaTabla();
            limpiarDatos();            
        } else {
            JOptionPane.showMessageDialog(this, "Atencion no eliminada");
        }
    }//GEN-LAST:event_eliminarButtonMAMouseClicked

    private void modificarButtonMAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarButtonMAMouseClicked
        try {
            int idAtencion = Integer.parseInt(txtIdAtencion.getText());
            String rut = txtRutPaciente.getText();
            String nombre = txtNombrePaciente.getText();
            Date fechaNacimiento = format.parse(txtFechaNacimiento.getText());
            int idEspecialidad = mapEspecialidad.get(cmbEspecialidad.getSelectedItem().toString());
            int idSistemaDeSalud = mapSistemaDeSalud.get(cmbSistemaDeSalud.getSelectedItem().toString());
            
            Atencion at = new Atencion();
            at.setIdAtencion(idAtencion);
            at.setRutPaciente(rut);
            at.setNombrePaciente(nombre);
            at.setFechaNacimientoPaciente(fechaNacimiento);
            at.setIdEspecialidad(idEspecialidad);
            at.setIdSistemaDeSalud(idSistemaDeSalud);
            
            if(new negAtencion().modificarAtencion(at)) {
                JOptionPane.showMessageDialog(this, "Atencion modificada");
                refrescaTabla();
                limpiarDatos();
            } else {
                JOptionPane.showMessageDialog(this, "Atencion no modificada");
            }
            
        } catch (ParseException ex) {
            Logger.getLogger(frmMantenedorAtenciones.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Atencion no modificada");
            refrescaTabla();
            limpiarDatos();
        }
    }//GEN-LAST:event_modificarButtonMAMouseClicked

    private void txtRutPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutPacienteKeyTyped
        char key = evt.getKeyChar();

        if (Character.isLetter(key)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "No se permiten letras en este campo");
        }
        
        if (txtRutPaciente.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRutPacienteKeyTyped

    private void txtFechaNacimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaNacimientoKeyTyped
        char key = evt.getKeyChar();

        if (Character.isLetter(key)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "No se permiten letras en este campo");
        }
        
        if (txtFechaNacimiento.getText().length() >= 10) {
            evt.consume();
        }
                  // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacimientoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMantenedorAtenciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMantenedorAtenciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMantenedorAtenciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMantenedorAtenciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMantenedorAtenciones().setVisible(true);
            }
        });
    }
    
    private void llenarTabla() {
        
        negAtencion neg = new negAtencion();
        ArrayList<Atencion> lista = neg.listarAtenciones();
        
        DefaultTableModel model = (DefaultTableModel) tblAtenciones.getModel();
        Object[] columnas = new Object[7];
        
        for (Atencion at : lista) {
            columnas[0] = at.getIdAtencion();
            columnas[1] = at.getRutPaciente();
            columnas[2] = at.getNombrePaciente();
            columnas[3] = at.getEdadPaciente();
            columnas[4] = at.getFechaNacimientoPaciente();
            columnas[5] = at.getEspecialidadPaciente();
            columnas[6] = at.getSistemaDeSaludPaciente();
            model.addRow(columnas);
        }
        
        tblAtenciones.setModel(model);       
    }
    
    private void refrescaTabla()
    {
       DefaultTableModel dm = (DefaultTableModel) tblAtenciones.getModel();
       dm.getDataVector().removeAllElements();
       llenarTabla();         
    }
    
    private void establecerId() {
        txtIdAtencion.setText(String.valueOf(new negAtencion().nextId()));
        txtRutPaciente.requestFocus();
    }
    
    private void limpiarDatos() {
        establecerId();
        txtRutPaciente.setText("");
        txtNombrePaciente.setText("");
        txtFechaNacimiento.setText("");
        cmbEspecialidad.setSelectedIndex(0);
        cmbSistemaDeSalud.setSelectedIndex(0);
        txtRutPaciente.requestFocus();
        
    }
    private void llenarCombos() {
        negEspecialidad negEsp = new negEspecialidad();
        negSistemaDeSalud negSdS = new negSistemaDeSalud();
        
        ArrayList<Especialidad> listaEsp = negEsp.listarTodo();
        ArrayList<SistemaDeSalud> listaSds = negSdS.listarTodo();
        
        for (SistemaDeSalud sds : listaSds) {
            mapSistemaDeSalud.put(sds.getNombreSistemaDeSalud(), sds.getIdSistemaDeSalud());
            cmbSistemaDeSalud.addItem(sds.getNombreSistemaDeSalud());
        }
        
        for (Especialidad esp : listaEsp) {
            mapEspecialidad.put(esp.getNombreEspecialidad(), esp.getIdEspecialidad());
            cmbEspecialidad.addItem(esp.getNombreEspecialidad());
        }
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icon;
    private javax.swing.JPanel MainMenuBg;
    private javax.swing.JLabel OPCIONEStxt;
    private javax.swing.JLabel Tiltetxt;
    private javax.swing.JPanel TitleMenu;
    private javax.swing.JPanel ZonaBg;
    private javax.swing.JPanel ZonaTableBg;
    private javax.swing.JPanel agregarButtonMA;
    private javax.swing.JLabel agregartxt;
    private javax.swing.JPanel cerrarsesionButtonMA;
    private javax.swing.JLabel cerrarsesiontxt;
    private javax.swing.JComboBox<String> cmbEspecialidad;
    private javax.swing.JComboBox<String> cmbSistemaDeSalud;
    private javax.swing.JPanel eliminarButtonMA;
    private javax.swing.JLabel eliminartxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblEspecialidad;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblFechaNacimiento1;
    private javax.swing.JLabel lblIdAtencion;
    private javax.swing.JLabel lblNombrePaciente;
    private javax.swing.JLabel lblRutPaciente;
    private javax.swing.JLabel lblSistemaDeSalud;
    private javax.swing.JPanel mainmenuButtonMA;
    private javax.swing.JPanel modificarButtonMA;
    private javax.swing.JLabel modificartxt;
    private javax.swing.JTable tblAtenciones;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtIdAtencion;
    private javax.swing.JTextField txtNombrePaciente;
    private javax.swing.JTextField txtRutPaciente;
    private javax.swing.JLabel volvermenutxt;
    // End of variables declaration//GEN-END:variables
}
